# Screen settings
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
FPS = 60

# Colors (RGB)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
ORANGE = (255, 165, 0)  # Orange
YELLOW = (255, 255, 0)  # Yellow

# Paddle settings
PADDLE_WIDTH = 120
PADDLE_HEIGHT = 15
PADDLE_SPEED = 450 # pixels per second
PADDLE_Y = SCREEN_HEIGHT - 40

# Ball settings
BALL_SIZE = 12
BALL_SPEED = 380  # pixels per second
BALL_START_X = SCREEN_WIDTH // 2
BALL_START_Y = SCREEN_HEIGHT - 70

# Brick settings
BRICK_ROWS = 6
BRICK_COLS = 10
BRICK_PADDING = 6
BRICK_TOP_OFFSET = 60
BRICK_WIDTH = (SCREEN_WIDTH - (BRICK_COLS + 1) * BRICK_PADDING) // BRICK_COLS
TOTAL_BRICK_WIDTH = BRICK_COLS * (BRICK_WIDTH + BRICK_PADDING) - BRICK_PADDING
BRICK_LEFT_OFFSET = (SCREEN_WIDTH - TOTAL_BRICK_WIDTH) // 2
BRICK_HEIGHT = 20
