WINDOW_TITLE = "TypeMaster - Typing Speed Analyzer"

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 650

BACKGROUND_COLOR = "#1E1E1E"
TEXT_COLOR = "#FFFFFF"

FONT_FAMILY = "Arial"

MAIN_FONT_SIZE = 22
STAT_FONT_SIZE = 16