WINDOW_TITLE = "TypeMaster - Typing Speed Analyzer"

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 800

BACKGROUND_COLOR = "#1E1E1E"
TEXT_COLOR = "#FFFFFF"

FONT_FAMILY = "Arial"

MAIN_FONT_SIZE = 22
STAT_FONT_SIZE = 16

TITLE_FONT = ("Segoe UI", 30, "bold")

SUBTITLE_FONT = ("Segoe UI", 11)

TEXT_FONT = ("Consolas", 16)

STAT_TITLE_FONT = ("Segoe UI", 10)

STAT_VALUE_FONT = ("Segoe UI", 20, "bold")

BUTTON_FONT = ("Segoe UI", 11, "bold")

# ---------- Colors ----------

BACKGROUND_COLOR = "#1B1D23"
CARD_COLOR = "#252932"

PRIMARY_TEXT = "#E5E9F0"
SECONDARY_TEXT = "#7F8794"

CORRECT_COLOR = "#A3BE8C"
ERROR_COLOR = "#BF616A"
CURRENT_COLOR = "#EBCB8B"

ACCENT_COLOR = "#88C0D0"

BUTTON_COLOR = "#3B4252"
BUTTON_HOVER = "#4C566A"